kind = "DojoContract"
class_hash = "0x16795fb9daacd22359e5a2a7cfb73b0eee1243fe36268e0fbbead0d927acb8e"
original_class_hash = "0x16795fb9daacd22359e5a2a7cfb73b0eee1243fe36268e0fbbead0d927acb8e"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_arena_arena.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::arena::arena"
