kind = "DojoContract"
class_hash = "0x47e2c187dd2836f117c119a7f39e1896ee59e6947176442d2482dee7d00804c"
original_class_hash = "0x47e2c187dd2836f117c119a7f39e1896ee59e6947176442d2482dee7d00804c"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_player_player.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::player::player"
