kind = "DojoContract"
class_hash = "0x2ae2ff2ba8e42b697e4cc950561027c1c27627592f219c84ac522451ff5b786"
original_class_hash = "0x2ae2ff2ba8e42b697e4cc950561027c1c27627592f219c84ac522451ff5b786"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_senzubean_senzubean.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::senzubean::senzubean"
