[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0xb4079627ebab1cd3cf9fd075dda1ad2454a7a448bf659591f259efa2519b18"
transaction_hash = "0x3a729aa09b4ad351fbc724f94c6d599037a53d7d9b5a182097a60fb09d0486c"
block_number = 3
seed = "dojo_starter"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x68dbbcc8da92234efb6f0854ac7bda623e45bab07b29657c795b80d027d611"
class_hash = "0x1008fb9b518ee84b355e0cd2fcb95ab662eabc959365e25e39b1f342ebee96c"
original_class_hash = "0x1008fb9b518ee84b355e0cd2fcb95ab662eabc959365e25e39b1f342ebee96c"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_starter_systems_arena_arena.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::arena::arena"

[[contracts]]
kind = "DojoContract"
address = "0x2c3b2e02437c686291121847040fada51eaeed0bac4a9a5160159316128f31"
class_hash = "0x1ba5ecf0020baf8cab85c2ef4af71468fd6a365f1c2979266797f441b0b1223"
original_class_hash = "0x1ba5ecf0020baf8cab85c2ef4af71468fd6a365f1c2979266797f441b0b1223"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_starter_systems_enemy_enemy.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::enemy::enemy"

[[contracts]]
kind = "DojoContract"
address = "0x353d00f00d802c4bf0958b26e4a82f6feaf4809c14f4316e4d97f32b12d0b2c"
class_hash = "0x64bc79d5f7c503633d88e062331683a51326430014fc57b8fb2571a26d16baf"
original_class_hash = "0x64bc79d5f7c503633d88e062331683a51326430014fc57b8fb2571a26d16baf"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_starter_systems_player_player.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::player::player"

[[contracts]]
kind = "DojoContract"
address = "0x3538033eccc74691dbd6aab9b4d63c51d667d42bc2aa17633a391c8b5486bdb"
class_hash = "0x2ae2ff2ba8e42b697e4cc950561027c1c27627592f219c84ac522451ff5b786"
original_class_hash = "0x2ae2ff2ba8e42b697e4cc950561027c1c27627592f219c84ac522451ff5b786"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_starter_systems_senzubean_senzubean.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::senzubean::senzubean"

[[models]]
kind = "DojoModel"
class_hash = "0x53abafbdde431771a8c09792becd1de91e7c631ad2707106a03a9407bd9cf45"
original_class_hash = "0x53abafbdde431771a8c09792becd1de91e7c631ad2707106a03a9407bd9cf45"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_arena_arena.json"
name = "dojo_starter::models::arena::arena"

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "bounds"
type = "Vec2D"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x34f13cbb9d3b9e76892cc5b7c41437860ca65665c1e88ee93cc43fadfebb5b4"
original_class_hash = "0x34f13cbb9d3b9e76892cc5b7c41437860ca65665c1e88ee93cc43fadfebb5b4"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_enemy_dice.json"
name = "dojo_starter::models::enemy::dice"

[[models.members]]
name = "face_count"
type = "u8"
key = true

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models.members]]
name = "nonce"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5434e411f94339d79a24296abea435e045a9213a6abde6fadac3f11d5523efb"
original_class_hash = "0x5434e411f94339d79a24296abea435e045a9213a6abde6fadac3f11d5523efb"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_enemy_enemy_attack.json"
name = "dojo_starter::models::enemy::enemy_attack"

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "location"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1c8251b68c4a99c10a54803b2c8371fedaeea25dd718c5b8a71ea9cb04988af"
original_class_hash = "0x1c8251b68c4a99c10a54803b2c8371fedaeea25dd718c5b8a71ea9cb04988af"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_player_player.json"
name = "dojo_starter::models::player::player"

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "position"
type = "Vec2D"
key = false

[[models.members]]
name = "health"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4766a9d5a0b872aa52f21982762e19924c78b0c4de2cd58329d03f7863bfcc3"
original_class_hash = "0x4766a9d5a0b872aa52f21982762e19924c78b0c4de2cd58329d03f7863bfcc3"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_senzubean_senzubean.json"
name = "dojo_starter::models::senzubean::senzubean"

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "point"
type = "Vec2D"
key = false

[[models.members]]
name = "is_eaten"
type = "bool"
key = false
